name: Deploy Allure Report

on:
  push:
    branches: [main]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v3

      - name: Set up Java
        uses: actions/setup-java@v3
        with:
          distribution: 'temurin'
          java-version: '11'

      - name: Print Java version
        run: java -version

      - name: Install Allure CLI
        run: npm install -g allure-commandline --save-dev

      - name: Run Tests
        run: ./gradlew clean test
        working-directory: ./api-framework

      - name: Generate Allure Report
        run: allure generate --clean -o allure-report
        working-directory: ./api-framework

      - name: Deploy Allure Report to GitHub Pages
        uses: peaceiris/actions-gh-pages@v3
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./api-framework/allure-report
